[package]
name = "week-day"
version = "0.1.0"
authors = ["Sebastian Steiner <e11777731@student.tuwien.ac.at>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.0"
chrono = "0.4.7"
